/*
  Simple DirectMedia Layer
  Copyright (C) 2025 Julien Sagot <contact@sagotch.fr>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

/* Provide dummy implementations for function exposed in the API by SDL
   releases that has been removed from TG2040 build because unrelevant */

#include "SDL_dummy.h"

#define SDL_DUMMY(ret_type, name, params, ret_value) \
  ret_type name##_REAL params                        \
  {                                                  \
    ret_type dummy = ret_value;                      \
    return dummy;                                    \
  }

#define SDL_DUMMY_VOID(name, params) \
  void name##_REAL params { return; }

#define DUMMY_SDL_GameControllerButtonBind {.bindType = SDL_CONTROLLER_BINDTYPE_NONE, .value = {.button = -1}}
#define DUMMY_SDL_GUID {0}

SDL_DUMMY(int, SDL_GL_LoadLibrary, (const char *a), -1)
SDL_DUMMY(void *, SDL_GL_GetProcAddress, (const char *a), NULL)
SDL_DUMMY_VOID(SDL_GL_UnloadLibrary, (void))
SDL_DUMMY(SDL_bool, SDL_GL_ExtensionSupported, (const char *a), SDL_FALSE)
SDL_DUMMY(int, SDL_GL_SetAttribute, (SDL_GLattr a, int b), -1)
SDL_DUMMY(int, SDL_GL_GetAttribute, (SDL_GLattr a, int *b), -1)
SDL_DUMMY(SDL_GLContext, SDL_GL_CreateContext, (SDL_Window * a), NULL)
SDL_DUMMY(int, SDL_GL_MakeCurrent, (SDL_Window * a, SDL_GLContext b), -1)
SDL_DUMMY(SDL_Window *, SDL_GL_GetCurrentWindow, (void), NULL)
SDL_DUMMY(SDL_GLContext, SDL_GL_GetCurrentContext, (void), NULL)
SDL_DUMMY_VOID(SDL_GL_GetDrawableSize, (SDL_Window * a, int *b, int *c))
SDL_DUMMY(int, SDL_GL_SetSwapInterval, (int a), -1)
SDL_DUMMY(int, SDL_GL_GetSwapInterval, (void), -1)
SDL_DUMMY_VOID(SDL_GL_SwapWindow, (SDL_Window * a))
SDL_DUMMY_VOID(SDL_GL_DeleteContext, (SDL_GLContext a))
SDL_DUMMY_VOID(SDL_GL_ResetAttributes, (void))
SDL_DUMMY(int, SDL_GL_BindTexture, (SDL_Texture * a, float *b, float *c), -1)
SDL_DUMMY(int, SDL_GL_UnbindTexture, (SDL_Texture * a), -1)
SDL_DUMMY(int, SDL_NumHaptics, (void), -1)
SDL_DUMMY(const char *, SDL_HapticName, (int a), NULL)
SDL_DUMMY(SDL_Haptic *, SDL_HapticOpen, (int a), NULL)
SDL_DUMMY(int, SDL_HapticOpened, (int a), -1)
SDL_DUMMY(int, SDL_HapticIndex, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_MouseIsHaptic, (void), -1)
SDL_DUMMY(SDL_Haptic *, SDL_HapticOpenFromMouse, (void), NULL)
SDL_DUMMY(int, SDL_JoystickIsHaptic, (SDL_Joystick * a), -1)
SDL_DUMMY(SDL_Haptic *, SDL_HapticOpenFromJoystick, (SDL_Joystick * a), NULL)
SDL_DUMMY_VOID(SDL_HapticClose, (SDL_Haptic * a))
SDL_DUMMY(int, SDL_HapticNumEffects, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_HapticNumEffectsPlaying, (SDL_Haptic * a), -1)
SDL_DUMMY(unsigned int, SDL_HapticQuery, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_HapticNumAxes, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_HapticEffectSupported, (SDL_Haptic * a, SDL_HapticEffect *b), -1)
SDL_DUMMY(int, SDL_HapticNewEffect, (SDL_Haptic * a, SDL_HapticEffect *b), -1)
SDL_DUMMY(int, SDL_HapticUpdateEffect, (SDL_Haptic * a, int b, SDL_HapticEffect *c), -1)
SDL_DUMMY(int, SDL_HapticRunEffect, (SDL_Haptic * a, int b, Uint32 c), -1)
SDL_DUMMY(int, SDL_HapticStopEffect, (SDL_Haptic * a, int b), -1)
SDL_DUMMY_VOID(SDL_HapticDestroyEffect, (SDL_Haptic * a, int b))
SDL_DUMMY(int, SDL_HapticGetEffectStatus, (SDL_Haptic * a, int b), -1)
SDL_DUMMY(int, SDL_HapticSetGain, (SDL_Haptic * a, int b), -1)
SDL_DUMMY(int, SDL_HapticSetAutocenter, (SDL_Haptic * a, int b), -1)
SDL_DUMMY(int, SDL_HapticPause, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_HapticUnpause, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_HapticStopAll, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_HapticRumbleSupported, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_HapticRumbleInit, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_HapticRumblePlay, (SDL_Haptic * a, float b, Uint32 c), -1)
SDL_DUMMY(int, SDL_HapticRumbleStop, (SDL_Haptic * a), -1)
SDL_DUMMY(int, SDL_Vulkan_LoadLibrary, (const char *a), -1)
SDL_DUMMY(void *, SDL_Vulkan_GetVkGetInstanceProcAddr, (void), NULL)
SDL_DUMMY_VOID(SDL_Vulkan_UnloadLibrary, (void))
SDL_DUMMY(SDL_bool, SDL_Vulkan_GetInstanceExtensions, (SDL_Window * a, unsigned int *b, const char **c), SDL_FALSE)
SDL_DUMMY(SDL_bool, SDL_Vulkan_CreateSurface, (SDL_Window * a, VkInstance b, VkSurfaceKHR *c), SDL_FALSE)
SDL_DUMMY_VOID(SDL_Vulkan_GetDrawableSize, (SDL_Window * a, int *b, int *c))
SDL_DUMMY(SDL_MetalView, SDL_Metal_CreateView, (SDL_Window * a), NULL)
SDL_DUMMY_VOID(SDL_Metal_DestroyView, (SDL_MetalView a))
SDL_DUMMY(void *, SDL_Metal_GetLayer, (SDL_MetalView a), NULL)
SDL_DUMMY_VOID(SDL_Metal_GetDrawableSize, (SDL_Window * a, int *b, int *c))
SDL_DUMMY(int, SDL_NumSensors, (void), -1)
SDL_DUMMY(const char *, SDL_SensorGetDeviceName, (int a), NULL)
SDL_DUMMY(SDL_SensorType, SDL_SensorGetDeviceType, (int a), SDL_SENSOR_INVALID)
SDL_DUMMY(int, SDL_SensorGetDeviceNonPortableType, (int a), -1)
SDL_DUMMY(SDL_SensorID, SDL_SensorGetDeviceInstanceID, (int a), -1)
SDL_DUMMY(SDL_Sensor *, SDL_SensorOpen, (int a), NULL)
SDL_DUMMY(SDL_Sensor *, SDL_SensorFromInstanceID, (SDL_SensorID a), NULL)
SDL_DUMMY(const char *, SDL_SensorGetName, (SDL_Sensor * a), NULL)
SDL_DUMMY(SDL_SensorType, SDL_SensorGetType, (SDL_Sensor * a), SDL_SENSOR_INVALID)
SDL_DUMMY(int, SDL_SensorGetNonPortableType, (SDL_Sensor * a), -1)
SDL_DUMMY(SDL_SensorID, SDL_SensorGetInstanceID, (SDL_Sensor * a), -1)
SDL_DUMMY(int, SDL_SensorGetData, (SDL_Sensor * a, float *b, int c), -1)
SDL_DUMMY_VOID(SDL_SensorClose, (SDL_Sensor * a))
SDL_DUMMY_VOID(SDL_SensorUpdate, (void))
SDL_DUMMY(int, SDL_GameControllerAddMapping, (const char *a), -1)
SDL_DUMMY(char *, SDL_GameControllerMappingForGUID, (SDL_JoystickGUID a), NULL)
SDL_DUMMY(char *, SDL_GameControllerMapping, (SDL_GameController * a), NULL)
SDL_DUMMY(SDL_bool, SDL_IsGameController, (int a), SDL_FALSE)
SDL_DUMMY(const char *, SDL_GameControllerNameForIndex, (int a), NULL)
SDL_DUMMY(SDL_GameController *, SDL_GameControllerOpen, (int a), NULL)
SDL_DUMMY(const char *, SDL_GameControllerName, (SDL_GameController * a), NULL)
SDL_DUMMY(SDL_bool, SDL_GameControllerGetAttached, (SDL_GameController * a), SDL_FALSE)
SDL_DUMMY(SDL_Joystick *, SDL_GameControllerGetJoystick, (SDL_GameController * a), NULL)
SDL_DUMMY(int, SDL_GameControllerEventState, (int a), -1)
SDL_DUMMY_VOID(SDL_GameControllerUpdate, (void))
SDL_DUMMY(SDL_GameControllerAxis, SDL_GameControllerGetAxisFromString, (const char *a), SDL_CONTROLLER_AXIS_INVALID)
SDL_DUMMY(const char *, SDL_GameControllerGetStringForAxis, (SDL_GameControllerAxis a), NULL)
SDL_DUMMY(SDL_GameControllerButtonBind, SDL_GameControllerGetBindForAxis, (SDL_GameController * a, SDL_GameControllerAxis b), DUMMY_SDL_GameControllerButtonBind)
SDL_DUMMY(Sint16, SDL_GameControllerGetAxis, (SDL_GameController * a, SDL_GameControllerAxis b), 0)
SDL_DUMMY(SDL_GameControllerButton, SDL_GameControllerGetButtonFromString, (const char *a), SDL_CONTROLLER_BUTTON_INVALID)
SDL_DUMMY(const char *, SDL_GameControllerGetStringForButton, (SDL_GameControllerButton a), NULL)
SDL_DUMMY(SDL_GameControllerButtonBind, SDL_GameControllerGetBindForButton, (SDL_GameController * a, SDL_GameControllerButton b), DUMMY_SDL_GameControllerButtonBind)
SDL_DUMMY(Uint8, SDL_GameControllerGetButton, (SDL_GameController * a, SDL_GameControllerButton b), -1)
SDL_DUMMY_VOID(SDL_GameControllerClose, (SDL_GameController * a))
SDL_DUMMY(int, SDL_RecordGesture, (SDL_TouchID a), -1)
SDL_DUMMY(int, SDL_SaveAllDollarTemplates, (SDL_RWops * a), -1)
SDL_DUMMY(int, SDL_SaveDollarTemplate, (SDL_GestureID a, SDL_RWops *b), -1)
SDL_DUMMY(int, SDL_LoadDollarTemplates, (SDL_TouchID a, SDL_RWops *b), -1)
SDL_DUMMY(int, SDL_NumJoysticks, (void), -1)
SDL_DUMMY(const char *, SDL_JoystickNameForIndex, (int a), NULL)
SDL_DUMMY(SDL_Joystick *, SDL_JoystickOpen, (int a), NULL)
SDL_DUMMY(const char *, SDL_JoystickName, (SDL_Joystick * a), NULL)
SDL_DUMMY(SDL_JoystickGUID, SDL_JoystickGetDeviceGUID, (int a), DUMMY_SDL_GUID)
SDL_DUMMY(SDL_JoystickGUID, SDL_JoystickGetGUID, (SDL_Joystick * a), DUMMY_SDL_GUID)
SDL_DUMMY_VOID(SDL_JoystickGetGUIDString, (SDL_JoystickGUID a, char *b, int c))
SDL_DUMMY(SDL_JoystickGUID, SDL_JoystickGetGUIDFromString, (const char *a), DUMMY_SDL_GUID)
SDL_DUMMY(SDL_bool, SDL_JoystickGetAttached, (SDL_Joystick * a), SDL_FALSE)
SDL_DUMMY(SDL_JoystickID, SDL_JoystickInstanceID, (SDL_Joystick * a), DUMMY_SDL_GUID)
SDL_DUMMY(int, SDL_JoystickNumAxes, (SDL_Joystick * a), -1)
SDL_DUMMY(int, SDL_JoystickNumBalls, (SDL_Joystick * a), -1)
SDL_DUMMY(int, SDL_JoystickNumHats, (SDL_Joystick * a), -1)
SDL_DUMMY(int, SDL_JoystickNumButtons, (SDL_Joystick * a), -1)
SDL_DUMMY_VOID(SDL_JoystickUpdate, (void))
SDL_DUMMY(int, SDL_JoystickEventState, (int a), -1)
SDL_DUMMY(Sint16, SDL_JoystickGetAxis, (SDL_Joystick * a, int b), -1)
SDL_DUMMY(Uint8, SDL_JoystickGetHat, (SDL_Joystick * a, int b), -1)
SDL_DUMMY(int, SDL_JoystickGetBall, (SDL_Joystick * a, int b, int *c, int *d), -1)
SDL_DUMMY(Uint8, SDL_JoystickGetButton, (SDL_Joystick * a, int b), -1)
SDL_DUMMY_VOID(SDL_JoystickClose, (SDL_Joystick * a))
SDL_DUMMY(SDL_Window *, SDL_GetMouseFocus, (void), NULL)
SDL_DUMMY(Uint32, SDL_GetMouseState, (int *a, int *b), -1)
SDL_DUMMY(Uint32, SDL_GetRelativeMouseState, (int *a, int *b), -1)
SDL_DUMMY_VOID(SDL_WarpMouseInWindow, (SDL_Window * a, int b, int c))
SDL_DUMMY(int, SDL_SetRelativeMouseMode, (SDL_bool a), -1)
SDL_DUMMY(SDL_bool, SDL_GetRelativeMouseMode, (void), SDL_FALSE)
SDL_DUMMY(SDL_Cursor *, SDL_CreateCursor, (const Uint8 *a, const Uint8 *b, int c, int d, int e, int f), NULL)
SDL_DUMMY(SDL_Cursor *, SDL_CreateColorCursor, (SDL_Surface * a, int b, int c), NULL)
SDL_DUMMY(SDL_Cursor *, SDL_CreateSystemCursor, (SDL_SystemCursor a), NULL)
SDL_DUMMY_VOID(SDL_SetCursor, (SDL_Cursor * a))
SDL_DUMMY(SDL_Cursor *, SDL_GetCursor, (void), NULL)
SDL_DUMMY(SDL_Cursor *, SDL_GetDefaultCursor, (void), NULL)
SDL_DUMMY_VOID(SDL_FreeCursor, (SDL_Cursor * a))
SDL_DUMMY(int, SDL_ShowCursor, (int a), -1)
SDL_DUMMY(int, SDL_GetNumTouchDevices, (void), -1)
SDL_DUMMY(SDL_TouchID, SDL_GetTouchDevice, (int a), -1)
SDL_DUMMY(int, SDL_GetNumTouchFingers, (SDL_TouchID a), -1)
SDL_DUMMY(SDL_Finger *, SDL_GetTouchFinger, (SDL_TouchID a, int b), NULL)
SDL_DUMMY(int, SDL_GameControllerAddMappingsFromRW, (SDL_RWops * a, int b), -1)
SDL_DUMMY(int, SDL_WarpMouseGlobal, (int a, int b), -1)
SDL_DUMMY(int, SDL_CaptureMouse, (SDL_bool a), -1)
SDL_DUMMY(Uint32, SDL_GetGlobalMouseState, (int *a, int *b), -1)
SDL_DUMMY(SDL_JoystickPowerLevel, SDL_JoystickCurrentPowerLevel, (SDL_Joystick * a), SDL_JOYSTICK_POWER_UNKNOWN)
SDL_DUMMY(SDL_GameController *, SDL_GameControllerFromInstanceID, (SDL_JoystickID a), NULL)
SDL_DUMMY(SDL_Joystick *, SDL_JoystickFromInstanceID, (SDL_JoystickID a), NULL)
SDL_DUMMY(Uint16, SDL_JoystickGetDeviceVendor, (int a), -1)
SDL_DUMMY(Uint16, SDL_JoystickGetDeviceProduct, (int a), -1)
SDL_DUMMY(Uint16, SDL_JoystickGetDeviceProductVersion, (int a), -1)
SDL_DUMMY(Uint16, SDL_JoystickGetVendor, (SDL_Joystick * a), -1)
SDL_DUMMY(Uint16, SDL_JoystickGetProduct, (SDL_Joystick * a), -1)
SDL_DUMMY(Uint16, SDL_JoystickGetProductVersion, (SDL_Joystick * a), -1)
SDL_DUMMY(Uint16, SDL_GameControllerGetVendor, (SDL_GameController * a), -1)
SDL_DUMMY(Uint16, SDL_GameControllerGetProduct, (SDL_GameController * a), -1)
SDL_DUMMY(Uint16, SDL_GameControllerGetProductVersion, (SDL_GameController * a), -1)
SDL_DUMMY(int, SDL_GameControllerNumMappings, (void), -1)
SDL_DUMMY(char *, SDL_GameControllerMappingForIndex, (int a), NULL)
SDL_DUMMY(SDL_bool, SDL_JoystickGetAxisInitialState, (SDL_Joystick * a, int b, Sint16 *c), SDL_FALSE)
SDL_DUMMY(SDL_JoystickType, SDL_JoystickGetDeviceType, (int a), SDL_JOYSTICK_TYPE_UNKNOWN)
SDL_DUMMY(SDL_JoystickType, SDL_JoystickGetType, (SDL_Joystick * a), SDL_JOYSTICK_TYPE_UNKNOWN)
SDL_DUMMY(SDL_JoystickID, SDL_JoystickGetDeviceInstanceID, (int a), -1)
SDL_DUMMY_VOID(SDL_LockJoysticks, (void))
SDL_DUMMY_VOID(SDL_UnlockJoysticks, (void))

SDL_DUMMY(char *, SDL_GameControllerMappingForDeviceIndex, (int a), NULL)
SDL_DUMMY(int, SDL_GameControllerRumble, (SDL_GameController * a, Uint16 b, Uint16 c, Uint32 d), -1)
SDL_DUMMY(int, SDL_JoystickRumble, (SDL_Joystick * a, Uint16 b, Uint16 c, Uint32 d), -1)
SDL_DUMMY(int, SDL_JoystickGetDevicePlayerIndex, (int a), -1)
SDL_DUMMY(int, SDL_JoystickGetPlayerIndex, (SDL_Joystick * a), -1)
SDL_DUMMY(int, SDL_GameControllerGetPlayerIndex, (SDL_GameController * a), -1)
SDL_DUMMY(SDL_TouchDeviceType, SDL_GetTouchDeviceType, (SDL_TouchID a), SDL_TOUCH_DEVICE_INVALID)
SDL_DUMMY(SDL_GameControllerType, SDL_GameControllerTypeForIndex, (int a), SDL_CONTROLLER_TYPE_UNKNOWN)
SDL_DUMMY(SDL_GameControllerType, SDL_GameControllerGetType, (SDL_GameController * a), SDL_CONTROLLER_TYPE_UNKNOWN)
SDL_DUMMY(SDL_GameController *, SDL_GameControllerFromPlayerIndex, (int a), NULL)
SDL_DUMMY_VOID(SDL_GameControllerSetPlayerIndex, (SDL_GameController * a, int b))
SDL_DUMMY(SDL_Joystick *, SDL_JoystickFromPlayerIndex, (int a), NULL)
SDL_DUMMY_VOID(SDL_JoystickSetPlayerIndex, (SDL_Joystick * a, int b))
SDL_DUMMY(int, SDL_JoystickAttachVirtual, (SDL_JoystickType a, int b, int c, int d), -1)
SDL_DUMMY(int, SDL_JoystickDetachVirtual, (int a), -1)
SDL_DUMMY(SDL_bool, SDL_JoystickIsVirtual, (int a), SDL_FALSE)
SDL_DUMMY(int, SDL_JoystickSetVirtualAxis, (SDL_Joystick * a, int b, Sint16 c), -1)
SDL_DUMMY(int, SDL_JoystickSetVirtualButton, (SDL_Joystick * a, int b, Uint8 c), -1)
SDL_DUMMY(int, SDL_JoystickSetVirtualHat, (SDL_Joystick * a, int b, Uint8 c), -1)
SDL_DUMMY_VOID(SDL_LockSensors, (void))
SDL_DUMMY_VOID(SDL_UnlockSensors, (void))
SDL_DUMMY(SDL_bool, SDL_GameControllerHasLED, (SDL_GameController * a), SDL_FALSE)
SDL_DUMMY(int, SDL_GameControllerSetLED, (SDL_GameController * a, Uint8 b, Uint8 c, Uint8 d), -1)
SDL_DUMMY(SDL_bool, SDL_JoystickHasLED, (SDL_Joystick * a), SDL_FALSE)
SDL_DUMMY(int, SDL_JoystickSetLED, (SDL_Joystick * a, Uint8 b, Uint8 c, Uint8 d), -1)
SDL_DUMMY(int, SDL_GameControllerRumbleTriggers, (SDL_GameController * a, Uint16 b, Uint16 c, Uint32 d), -1)
SDL_DUMMY(int, SDL_JoystickRumbleTriggers, (SDL_Joystick * a, Uint16 b, Uint16 c, Uint32 d), -1)
SDL_DUMMY(SDL_bool, SDL_GameControllerHasAxis, (SDL_GameController * a, SDL_GameControllerAxis b), SDL_FALSE)
SDL_DUMMY(SDL_bool, SDL_GameControllerHasButton, (SDL_GameController * a, SDL_GameControllerButton b), SDL_FALSE)
SDL_DUMMY(int, SDL_GameControllerGetNumTouchpads, (SDL_GameController * a), -1)
SDL_DUMMY(int, SDL_GameControllerGetNumTouchpadFingers, (SDL_GameController * a, int b), -1)
SDL_DUMMY(int, SDL_GameControllerGetTouchpadFinger, (SDL_GameController * a, int b, int c, Uint8 *d, float *e, float *f, float *g), -1)
SDL_DUMMY(const char *, SDL_GameControllerGetSerial, (SDL_GameController * a), NULL)
SDL_DUMMY(const char *, SDL_JoystickGetSerial, (SDL_Joystick * a), NULL)
SDL_DUMMY(SDL_bool, SDL_GameControllerHasSensor, (SDL_GameController * a, SDL_SensorType b), SDL_FALSE)
SDL_DUMMY(int, SDL_GameControllerSetSensorEnabled, (SDL_GameController * a, SDL_SensorType b, SDL_bool c), -1)
SDL_DUMMY(SDL_bool, SDL_GameControllerIsSensorEnabled, (SDL_GameController * a, SDL_SensorType b), SDL_FALSE)
SDL_DUMMY(int, SDL_GameControllerGetSensorData, (SDL_GameController * a, SDL_SensorType b, float *c, int d), -1)
SDL_DUMMY_VOID(SDL_SetWindowMouseGrab, (SDL_Window * a, SDL_bool b))
SDL_DUMMY(SDL_bool, SDL_GetWindowMouseGrab, (SDL_Window * a), SDL_FALSE)
SDL_DUMMY(int, SDL_GameControllerSendEffect, (SDL_GameController * a, const void *b, int c), -1)
SDL_DUMMY(int, SDL_JoystickSendEffect, (SDL_Joystick * a, const void *b, int c), -1)
SDL_DUMMY(float, SDL_GameControllerGetSensorDataRate, (SDL_GameController * a, SDL_SensorType b), 0)
SDL_DUMMY(const char *, SDL_GameControllerGetAppleSFSymbolsNameForButton, (SDL_GameController * a, SDL_GameControllerButton b), NULL)
SDL_DUMMY(const char *, SDL_GameControllerGetAppleSFSymbolsNameForAxis, (SDL_GameController * a, SDL_GameControllerAxis b), NULL)
SDL_DUMMY(int, SDL_hid_init, (void), -1)
SDL_DUMMY(int, SDL_hid_exit, (void), -1)
SDL_DUMMY(Uint32, SDL_hid_device_change_count, (void), -1)
SDL_DUMMY(SDL_hid_device_info *, SDL_hid_enumerate, (unsigned short a, unsigned short b), NULL)
SDL_DUMMY_VOID(SDL_hid_free_enumeration, (SDL_hid_device_info * a))
SDL_DUMMY(SDL_hid_device *, SDL_hid_open, (unsigned short a, unsigned short b, const wchar_t *c), NULL)
SDL_DUMMY(SDL_hid_device *, SDL_hid_open_path, (const char *a, int b), NULL)
SDL_DUMMY(int, SDL_hid_write, (SDL_hid_device * a, const unsigned char *b, size_t c), -1)
SDL_DUMMY(int, SDL_hid_read_timeout, (SDL_hid_device * a, unsigned char *b, size_t c, int d), -1)
SDL_DUMMY(int, SDL_hid_read, (SDL_hid_device * a, unsigned char *b, size_t c), -1)
SDL_DUMMY(int, SDL_hid_set_nonblocking, (SDL_hid_device * a, int b), -1)
SDL_DUMMY(int, SDL_hid_send_feature_report, (SDL_hid_device * a, const unsigned char *b, size_t c), -1)
SDL_DUMMY(int, SDL_hid_get_feature_report, (SDL_hid_device * a, unsigned char *b, size_t c), -1)
SDL_DUMMY_VOID(SDL_hid_close, (SDL_hid_device * a))
SDL_DUMMY(int, SDL_hid_get_manufacturer_string, (SDL_hid_device * a, wchar_t *b, size_t c), -1)
SDL_DUMMY(int, SDL_hid_get_product_string, (SDL_hid_device * a, wchar_t *b, size_t c), -1)
SDL_DUMMY(int, SDL_hid_get_serial_number_string, (SDL_hid_device * a, wchar_t *b, size_t c), -1)
SDL_DUMMY(int, SDL_hid_get_indexed_string, (SDL_hid_device * a, int b, wchar_t *c, size_t d), -1)
SDL_DUMMY(int, SDL_SetWindowMouseRect, (SDL_Window * a, const SDL_Rect *b), -1)
SDL_DUMMY(const SDL_Rect *, SDL_GetWindowMouseRect, (SDL_Window * a), NULL)
SDL_DUMMY(SDL_bool, SDL_JoystickHasRumble, (SDL_Joystick * a), SDL_FALSE)
SDL_DUMMY(SDL_bool, SDL_JoystickHasRumbleTriggers, (SDL_Joystick * a), SDL_FALSE)
SDL_DUMMY(SDL_bool, SDL_GameControllerHasRumble, (SDL_GameController * a), SDL_FALSE)
SDL_DUMMY(SDL_bool, SDL_GameControllerHasRumbleTriggers, (SDL_GameController * a), SDL_FALSE)
SDL_DUMMY_VOID(SDL_hid_ble_scan, (SDL_bool a))
SDL_DUMMY(const char *, SDL_GetTouchName, (int a), NULL)
SDL_DUMMY(const char *, SDL_GameControllerPathForIndex, (int a), NULL)
SDL_DUMMY(const char *, SDL_GameControllerPath, (SDL_GameController * a), NULL)
SDL_DUMMY(const char *, SDL_JoystickPathForIndex, (int a), NULL)
SDL_DUMMY(const char *, SDL_JoystickPath, (SDL_Joystick * a), NULL)
SDL_DUMMY(int, SDL_JoystickAttachVirtualEx, (const SDL_VirtualJoystickDesc *a), -1)
SDL_DUMMY(Uint16, SDL_GameControllerGetFirmwareVersion, (SDL_GameController * a), -1)
SDL_DUMMY(Uint16, SDL_JoystickGetFirmwareVersion, (SDL_Joystick * a), -1)
SDL_DUMMY_VOID(SDL_GetJoystickGUIDInfo, (SDL_JoystickGUID a, Uint16 *b, Uint16 *c, Uint16 *d, Uint16 *e))
SDL_DUMMY(int, SDL_GameControllerGetSensorDataWithTimestamp, (SDL_GameController * a, SDL_SensorType b, Uint64 *c, float *d, int e), -1)
SDL_DUMMY(int, SDL_SensorGetDataWithTimestamp, (SDL_Sensor * a, Uint64 *b, float *c, int d), -1)

#undef SDL_DUMMY
